import Head from "next/head";
import Features from "../components/Features";
import Intro from "../components/Intro";
import Layout from "../components/Layout";
import Products from "../components/Products";  
import { client } from "../lib/client";

export default function Home({watches}) {
    console.log({watches});
    return ( 
        <Layout home={true} products={false} about={false} offers={false}>

               <Head>
                    <title>Fawatch</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/Logo.png" />
                </Head>
                {/* body */} 
                <main>
                    <Intro/>
                    <Features/> 
                    <Products watches={watches}/>
                </main>

        </Layout>
    );
}
export const getServerSideProps = async()=>{
    const query='*[_type=="watch"]';
    const watches = await client.fetch(query); 
    return{
        props:{
            watches 
        }
    }
}
